### ISSUE TITLE
Sifter's Gambit does not play nice in Multiplayer servers

### ISSUE THREAD

**Issue by MeggalBozale** [Talia-12/MoreIotas#11]
Weird things happen after relogging when using sifter's gambit to listen for strings.
Expected behavior (Which was encountered in singleplayer):
- `Sifter's Gambit`, when passed a string, returns everything but that string when the caster types in chat.
- Passing null permanently stops `Sifter's gambit` from listening and `Listener's Reflection` functions as normal.

Encountered behavior in multiplayer:
- `Sifter's gambit` functions properly until you relog.
- First set of relogging caused `Sifter's Gambit`, which was passed `null` recently, to re-listen for the string `"0 10 0"`. It stopped when passed null, but kept listening again after another relog.
- Passing a new String to `Sifter's Gambit` and then `null`, then relogging, caused `Sifter's Gambit` to not listen for that string as expected. However, it no longer listens for any string, and `Listener's Reflection` returns the last message it seems to "remember" the caster saying until you pass `null` into `Sifter's Gambit` again, in which functionality resumes.

[Modlist](https://www.curseforge.com/minecraft/modpacks/uncharacteristically-generic-modern-experience)
My only suspicions is that a chat mod like `No Chat Reports` messes with `Sifter's Gambit` somehow, but I'm not quite sure.

![javaw_c7c2dkjNqm](https://github.com/Talia-12/MoreIotas/assets/27376947/72d854ee-0d14-41b3-9c9a-4a1b24e58e14)
Shown above is casting Sifter's Reflection before and after relogging. Note I had passed the string "goto " most recently to sifter's gambit, making this *Extra Spicy Weird*.

Tried my best to give as much information as humanly possible, but let me know if more is needed or if I'm goofing somehow, but I have also done my best to understand the spell and that this does indeed seem to be unintended behavior.

**Comment by Talia-12** [comment]
should be fixed for the next release.
