### ISSUE TITLE
Matrix size documentation is inconsistent and confusing

### ISSUE THREAD

**Issue by object-Object** [Talia-12/MoreIotas#12]
Preface: The width of a matrix is the number of columns. The height of a matrix is the number of rows. [Generally](url), this is denoted `m × n`, where `m` is the height (rows) and `n` is the width (columns). The iota string representation uses this order.
https://github.com/Talia-12/MoreIotas/blob/71e0b2c36f7a34ce2e332094882ab114557c32d6/Common/src/main/java/ram/talia/moreiotas/api/spell/iota/MatrixIota.java#L93

This is not explicitly stated anywhere in the book (unless I missed it), and some of the pattern docs don't follow this convention. For example, it's reversed in the descriptions of Tower and Sprawling:
![image](https://github.com/Talia-12/MoreIotas/assets/37044997/94fb61b2-5663-4772-9b0b-3018782784d0)
As an aside, the fact that `m` and `n` are swapped here is also very confusing.

Meanwhile, Transformation uses the correct order:
![image](https://github.com/Talia-12/MoreIotas/assets/37044997/f5c7900f-5eec-43ef-8cfe-49e0cfdffe2f)

**Comment by Talia-12** [comment]
Fixed for the next release.
