### ISSUE TITLE
warning: REI entrypoiny is deprecated

### ISSUE THREAD

**Issue by walksanatora** [Talia-12/MoreIotas#6]
just letting you know thet the `rei_plugin_v0` entrypoint is deprecated

**Comment by beep-beep-beep-boop** [comment]
this is causing a crash for me when running on a standalone server

**Comment by walksanatora** [comment]
so i think that this means it has gone from deprecated to removed

**Comment by walksanatora** [comment]
This still has not been fixed...

**Comment by Talia-12** [comment]
fixed for the next release!
